import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { StoreProvider } from "./redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <div>
            <Navbar />
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
