import "./globals.css";
import Navbar from "./Navbar";
import { StoreProvider } from "./redux/StoreProvider";
import Footer from "./Footer";
import AuthProvider from "@/Contexts/AuthProvider/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <StoreProvider>
        <html lang="en">
          <body>
            <div>
              <Navbar />
              {children}
              <Footer />
            </div>
          </body>
        </html>
      </StoreProvider>
    </AuthProvider>
  );
}

// "use client"
// import { useEffect, useState } from "react";
// import { StoreProvider } from "./redux/StoreProvider";
// import Navbar from "./Navbar";
// import Footer from "./Footer";
// import { useRouter } from "next/navigation";

// // Removed the export statement for metadata
// const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   const router = useRouter();

//   const [userLocation, setUserLocation] = useState(null);

//   useEffect(() => {
//     // Check if geolocation is supported by the browser
//     if ("geolocation" in navigator) {
//       navigator.geolocation.getCurrentPosition(
//         (position) => {
//           // Successfully retrieved the user's location
//           setUserLocation({
//             latitude: position.coords.latitude,
//             longitude: position.coords.longitude,
//           });
//         },
//         (error) => {
//           console.error("Error getting user location:", error.message);
//         }
//       );
//     } else {
//       console.error("Geolocation is not supported by your browser");
//     }
//   }, []);

//   return (
//     <StoreProvider>
//       <html lang="en">
//         <body>
//           <div>
//             <Navbar />
//             <p>User's Location: {userLocation ? `Lat: ${userLocation.latitude}, Long: ${userLocation.longitude}` : "Loading..."}</p>
//             {children}
//             <Footer />
//           </div>
//         </body>
//       </html>
//     </StoreProvider>
//   );
// }
